<?php

declare(strict_types=1);

namespace Icalendar\Tests\Recurrence;

use DateTimeImmutable;
use Icalendar\Component\VEvent;
use Icalendar\Component\VJournal;
use Icalendar\Component\VTodo;
use Icalendar\Property\GenericProperty;
use Icalendar\Recurrence\Occurrence;
use Icalendar\Recurrence\RecurrenceExpander;
use Icalendar\Value\TextValue;
use PHPUnit\Framework\TestCase;

class RecurrenceExpanderTest extends TestCase
{
    private RecurrenceExpander $expander;

    protected function setUp(): void
    {
        $this->expander = new RecurrenceExpander();
    }

    public function testExpandDailyCount(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(5, $occurrences);
        $this->assertEquals('2026-01-01 09:00:00', $occurrences[0]->getStart()->format('Y-m-d H:i:s'));
        $this->assertEquals('2026-01-05 09:00:00', $occurrences[4]->getStart()->format('Y-m-d H:i:s'));
        foreach ($occurrences as $occ) {
            $this->assertFalse($occ->isRdate());
        }
    }

    public function testExpandWeeklyWithDtEnd(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('DTEND', '20260101T100000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=WEEKLY;COUNT=3'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences);
        foreach ($occurrences as $occ) {
            $this->assertEquals('09:00:00', $occ->getStart()->format('H:i:s'));
            $this->assertEquals('10:00:00', $occ->getEnd()->format('H:i:s'));
            $this->assertEquals(3600, $occ->getEnd()->getTimestamp() - $occ->getStart()->getTimestamp());
        }
    }

    public function testExpandMonthlyWithDuration(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('DURATION', 'PT30M'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=MONTHLY;COUNT=3'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences);
        foreach ($occurrences as $occ) {
            $this->assertEquals('09:00:00', $occ->getStart()->format('H:i:s'));
            $this->assertEquals('09:30:00', $occ->getEnd()->format('H:i:s'));
        }
    }

    public function testExpandYearlyWithUntil(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=YEARLY;UNTIL=20280101T090000Z'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences); // 2026, 2027, 2028 (if UTC)
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2027-01-01', $occurrences[1]->getStart()->format('Y-m-d'));
        $this->assertEquals('2028-01-01', $occurrences[2]->getStart()->format('Y-m-d'));
    }

    public function testExdateExcludesOccurrence(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260103T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(4, $occurrences);
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-02', $occurrences[1]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-04', $occurrences[2]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-05', $occurrences[3]->getStart()->format('Y-m-d'));
    }

    public function testExdateAppliedAfterCount(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260103T090000'));

        $occurrences = $this->expander->expandToArray($event);

        // Per RFC 5545, EXDATE is applied to the set generated by RRULE.
        // A rule with COUNT=5 generates 5 candidates. 1 is excluded -> 4 results.
        $this->assertCount(4, $occurrences);
    }

    public function testExdateDateOnlyMatching(): void
    {
        $event = new VEvent();
        // VALUE=DATE DTSTART
        $dtstart = GenericProperty::create('DTSTART', '20260101');
        $dtstart->setParameter('VALUE', 'DATE');
        $event->addProperty($dtstart);
        
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));
        
        // VALUE=DATE EXDATE
        $exdate = GenericProperty::create('EXDATE', '20260103');
        $exdate->setParameter('VALUE', 'DATE');
        $event->addProperty($exdate);

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(4, $occurrences);
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-02', $occurrences[1]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-04', $occurrences[2]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-05', $occurrences[3]->getStart()->format('Y-m-d'));
    }

    public function testExdateCommaSeparated(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260102T090000,20260104T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences);
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-03', $occurrences[1]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-05', $occurrences[2]->getStart()->format('Y-m-d'));
    }

    public function testExdateMultipleProperties(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260102T090000'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260104T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences);
    }

    public function testExdateOnDtstart(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=3'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260101T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(2, $occurrences);
        $this->assertEquals('2026-01-02', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-03', $occurrences[1]->getStart()->format('Y-m-d'));
    }

    public function testRdateAddsOccurrence(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=3'));
        $event->addProperty(GenericProperty::create('RDATE', '20260105T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(4, $occurrences);
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-02', $occurrences[1]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-03', $occurrences[2]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-05', $occurrences[3]->getStart()->format('Y-m-d'));
        $this->assertTrue($occurrences[3]->isRdate());
    }

    public function testRdateDeduplicatesWithRrule(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=3'));
        $event->addProperty(GenericProperty::create('RDATE', '20260102T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(3, $occurrences);
    }

    public function testRdateOnlyNoRrule(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RDATE', '20260105T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(2, $occurrences);
        $this->assertEquals('2026-01-01', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-05', $occurrences[1]->getStart()->format('Y-m-d'));
    }

    public function testMultiRruleUnion(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260105T090000')); // Monday
        // Mondays for 3 weeks
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=WEEKLY;BYDAY=MO;COUNT=3'));
        // Wednesdays for 3 weeks
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=WEEKLY;BYDAY=WE;COUNT=3'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(6, $occurrences);
        $this->assertEquals('2026-01-05', $occurrences[0]->getStart()->format('Y-m-d')); // Mon
        $this->assertEquals('2026-01-07', $occurrences[1]->getStart()->format('Y-m-d')); // Wed
        $this->assertEquals('2026-01-12', $occurrences[2]->getStart()->format('Y-m-d')); // Mon
        $this->assertEquals('2026-01-14', $occurrences[3]->getStart()->format('Y-m-d')); // Wed
        $this->assertEquals('2026-01-19', $occurrences[4]->getStart()->format('Y-m-d')); // Mon
        $this->assertEquals('2026-01-21', $occurrences[5]->getStart()->format('Y-m-d')); // Wed
    }

    public function testMultiRruleSharedExdate(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260105T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=WEEKLY;BYDAY=MO;COUNT=3'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=WEEKLY;BYDAY=WE;COUNT=3'));
        $event->addProperty(GenericProperty::create('EXDATE', '20260107T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(5, $occurrences);
        $this->assertEquals('2026-01-05', $occurrences[0]->getStart()->format('Y-m-d'));
        $this->assertEquals('2026-01-12', $occurrences[1]->getStart()->format('Y-m-d'));
    }

    public function testUnboundedWithoutRangeEndThrows(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY'));

        $this->expectException(\InvalidArgumentException::class);
        $this->expander->expandToArray($event);
    }

    public function testUnboundedWithRangeEndWorks(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY'));
        
        $rangeEnd = new DateTimeImmutable('2026-01-05T23:59:59');
        $occurrences = $this->expander->expandToArray($event, $rangeEnd);

        $this->assertCount(5, $occurrences);
    }

    public function testCountBoundedWithoutRangeEnd(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $event->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=5'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(5, $occurrences);
    }

    public function testNoRruleNoRdate(): void
    {
        $event = new VEvent();
        $event->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));

        $occurrences = $this->expander->expandToArray($event);

        $this->assertCount(1, $occurrences);
        $this->assertEquals('2026-01-01 09:00:00', $occurrences[0]->getStart()->format('Y-m-d H:i:s'));
    }

    public function testVjournalEndIsNull(): void
    {
        $journal = new VJournal();
        $journal->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $journal->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=3'));

        $occurrences = $this->expander->expandToArray($journal);

        $this->assertCount(3, $occurrences);
        foreach ($occurrences as $occ) {
            $this->assertNull($occ->getEnd());
        }
    }

    public function testVtodoWithDue(): void
    {
        $todo = new VTodo();
        $todo->addProperty(GenericProperty::create('DTSTART', '20260101T090000'));
        $todo->addProperty(GenericProperty::create('DUE', '20260101T103000'));
        $todo->addProperty(GenericProperty::create('RRULE', 'FREQ=DAILY;COUNT=3'));

        $occurrences = $this->expander->expandToArray($todo);

        $this->assertCount(3, $occurrences);
        foreach ($occurrences as $occ) {
            $this->assertEquals(5400, $occ->getEnd()->getTimestamp() - $occ->getStart()->getTimestamp()); // 1.5 hours
        }
    }
}
